name: 'format-markdown-links'
description: "GitHub action to strip Markdown file extensions from links and remove leading subdirectories"
branding:
  icon: delete
  color: orange

inputs:
  path:
    description: Where to look for files to do operation
    required: true
  removeSubdirectories:
    description: Remove leading subdirectories from links
    required: false
    default: true
  failOnDuplicateNames:
    description: Fail if duplicate filenames are found
    required: false
    default: true

runs:
  using: 'node16'
  main: 'dist/index.js'
